//! Do not delete this file - it contains important examples of how to use the sidebar functionality
//--- IGNORE ---
'use client'
import React from 'react';
import { useSidebarActions, useContactSidebar, useReadingSidebar } from '@/hooks/useSidebarActions';
import { sidebarUtils } from '@/utils/sidebarUtils';
import PrimaryButton from '@/components/utils/buttons/PrimaryButton';

/**
 * Example component showing different ways to trigger the sidebar
 * This can be used anywhere in your app
 */
const SidebarExamples = () => {
  // Using hooks (inside React components)
  const { 
    showNavigation, 
    showContactForm, 
    showReadingContent, 
    showSpecificationsContent,
    showJobContent,
    showCustomContent,
    hideSidebar,
    toggleNav,
    isOpen
  } = useSidebarActions();
  
  const { inquireAboutProduct, inquireAboutService, generalInquiry, supportRequest } = useContactSidebar();
  const { showArticle, showBlogPost, showNews, showCaseStudy } = useReadingSidebar();

  // Example data for different content types
  const sampleArticle = {
    title: "Revolutionary Plasma Technology in Energy Production",
    content: `
      <p>Plasma technology represents a breakthrough in sustainable energy production. Our innovative approach to plasma-based systems offers unprecedented efficiency in converting waste materials into clean energy.</p>
      
      <h3>Key Benefits:</h3>
      <ul>
        <li>Zero emissions production</li>
        <li>99.9% conversion efficiency</li>
        <li>Scalable from industrial to residential applications</li>
        <li>Cost-effective implementation</li>
      </ul>
      
      <p>This technology addresses the growing need for sustainable energy solutions while providing economic benefits to organizations worldwide.</p>
    `,
    author: "Dr. Sarah Johnson",
    date: "October 13, 2025",
    readTime: "5 min read",
    category: "Technology",
    tags: ["plasma", "energy", "sustainability", "innovation"],
    relatedLinks: [
      { title: "Learn More About Our Technology", url: "https://graforce.com/technology" },
      { title: "Case Studies", url: "https://graforce.com/case-studies" }
    ],
    ctaText: "Contact Us for More Info",
    ctaAction: "contact"
  };

  const sampleSpecifications = {
    title: "Methane Plasmalyzer® Technical Specifications",
    content: {
      specifications: [
        {
          subtitle: "Performance Specifications",
          details: "High-performance plasma system designed for methane processing with industry-leading efficiency.",
          points: [
            "Processing capacity: 100-500 Nm³/h methane input",
            "Conversion efficiency: >99.9%",
            "Energy consumption: <15 kWh/kg H₂",
            "Operating temperature: 800-1200°C",
            "Pressure range: 1-10 bar"
          ]
        },
        {
          subtitle: "System Requirements",
          details: "Technical requirements and infrastructure needs for optimal operation.",
          points: [
            "Power supply: 380-480V, 50/60Hz",
            "Cooling water: 2-5 m³/h",
            "Compressed air: 6-8 bar",
            "Installation space: 6m x 4m x 3m",
            "Ambient temperature: 5-40°C"
          ]
        },
        {
          subtitle: "Output Products",
          details: "High-quality products generated by the plasma process.",
          points: [
            "Hydrogen purity: >99.95%",
            "Carbon black: 95-98% purity",
            "CO₂ avoidance: >90% vs. conventional methods",
            "Byproduct utilization: 100% carbon recovery"
          ]
        }
      ]
    },
    actions: [
      {
        label: "Request Quote",
        primary: true,
        onClick: "() => sidebarUtils.showProduct('Methane Plasmalyzer®', 'High-efficiency plasma system for methane processing')"
      },
      {
        label: "Download Specs",
        primary: false,
        onClick: "() => alert('Downloading specifications...')"
      }
    ]
  };

  const customContentExample = {
    title: "Custom Sidebar Content",
    description: "This is an example of custom content in the sidebar",
    content: (
      <div>
        <p className="text-gray-600 mb-4">You can put any React components here!</p>
        <div className="bg-blue-50 p-4 rounded-lg mb-4">
          <h4 className="font-semibold text-blue-800 mb-2">Features:</h4>
          <ul className="text-blue-700 space-y-1">
            <li>• Dynamic content loading</li>
            <li>• Custom styling</li>
            <li>• Interactive elements</li>
            <li>• Multiple content types support</li>
            <li>• Action buttons integration</li>
          </ul>
        </div>
        <div className="bg-green-50 p-4 rounded-lg">
          <h4 className="font-semibold text-green-800 mb-2">Available Content Types:</h4>
          <ul className="text-green-700 space-y-1">
            <li>• Navigation Menu</li>
            <li>• Contact Forms</li>
            <li>• Reading Content (Articles, Blogs, News)</li>
            <li>• Technical Specifications</li>
            <li>• Job Postings</li>
            <li>• Custom Components</li>
          </ul>
        </div>
      </div>
    ),
    actions: [
      {
        label: "Primary Action",
        primary: true,
        onClick: "() => alert('Primary action clicked!')"
      },
      {
        label: "Secondary Action", 
        primary: false,
        onClick: "() => alert('Secondary action clicked!')"
      }
    ]
  };

  const jobContentExample = {
    content: {
      title: "Senior Plasma Engineer",
      postedOn: "2025-10-10",
      location: "Berlin, Germany", 
      applyBy: "2025-11-15",
      aboutUs: "Graforce is a leading company in plasma technology for sustainable energy solutions. We're revolutionizing the energy sector with innovative plasma-based technologies.",
      aboutUsPoints: [
        "Pioneering plasma technology solutions for clean energy",
        "Focus on environmental sustainability and carbon reduction", 
        "Global leader in waste-to-energy conversion",
        "Award-winning research and development team",
        "Offices in Berlin, Munich, and expanding internationally"
      ],
      jobDescription: "We are looking for a Senior Plasma Engineer to join our innovative team and help develop next-generation plasma systems for sustainable energy production.",
      jobDescriptionPoints: [
        "Design and develop advanced plasma reactor systems",
        "Collaborate with cross-functional engineering teams",
        "Research new plasma applications for energy conversion",
        "Optimize existing plasma processes for maximum efficiency",
        "Lead technical documentation and patent applications",
        "Mentor junior engineers and coordinate project teams"
      ]
    },
    actions: [
      {
        label: "Apply Now",
        primary: true,
        onClick: "() => sidebarUtils.openContact({ subject: 'Job Application: Senior Plasma Engineer', showSubject: true, additionalInfo: 'I am interested in applying for the Senior Plasma Engineer position.' })"
      },
      {
        label: "Save Job",
        primary: false,
        onClick: "() => alert('Job saved to your favorites!')"
      }
    ]
  };

  return (
    <div className="p-6 max-w-4xl mx-auto">
      <h1 className="text-3xl font-bold mb-8">Sidebar Examples</h1>
      
      {/* Basic Sidebar Controls */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Basic Sidebar Controls</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
          <PrimaryButton onClick={showNavigation}>
            Show Navigation
          </PrimaryButton>
          <PrimaryButton onClick={() => showContactForm()}>
            Show Contact Form
          </PrimaryButton>
          <PrimaryButton onClick={() => showReadingContent(sampleArticle)}>
            Show Article
          </PrimaryButton>
          <PrimaryButton onClick={() => showSpecificationsContent(sampleSpecifications)}>
            Show Specifications
          </PrimaryButton>
          <PrimaryButton onClick={() => showJobContent(jobContentExample)}>
            Show Job Content
          </PrimaryButton>
          <PrimaryButton onClick={() => showCustomContent(customContentExample)}>
            Show Custom Content
          </PrimaryButton>
          <PrimaryButton onClick={hideSidebar} className="bg-red-500 hover:bg-red-600">
            Close Sidebar
          </PrimaryButton>
          <PrimaryButton onClick={toggleNav}>
            Toggle Navigation
          </PrimaryButton>
        </div>
        <div className="mt-4 p-4 bg-blue-50 rounded-lg">
          <p className="text-blue-800 font-semibold">
            Sidebar Status: {isOpen ? "Open" : "Closed"}
          </p>
        </div>
      </section>

      {/* Contact Examples */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Contact Form Examples</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          <PrimaryButton onClick={() => inquireAboutProduct("Methane Plasmalyzer®")}>
            Product Inquiry
          </PrimaryButton>
          <PrimaryButton onClick={() => inquireAboutService("Hydrogen Production")}>
            Service Inquiry
          </PrimaryButton>
          <PrimaryButton onClick={generalInquiry}>
            General Inquiry
          </PrimaryButton>
          <PrimaryButton onClick={supportRequest}>
            Support Request
          </PrimaryButton>
        </div>
        
        {/* Advanced Contact Examples */}
        <div className="mt-6">
          <h3 className="text-lg font-semibold mb-3">Advanced Contact Forms</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            <PrimaryButton onClick={() => showContactForm({
              subject: "Partnership Inquiry",
              showSubject: true,
              additionalInfo: "I'm interested in exploring partnership opportunities with Graforce."
            })}>
              Partnership Form
            </PrimaryButton>
            <PrimaryButton onClick={() => showContactForm({
              subject: "Technical Support",
              showSubject: true,
              additionalInfo: "I need technical assistance with one of your products."
            })}>
              Technical Support
            </PrimaryButton>
            <PrimaryButton onClick={() => showContactForm({
              subject: "Media Inquiry", 
              showSubject: true,
              additionalInfo: "I'm a journalist interested in interviewing your team."
            })}>
              Media Inquiry
            </PrimaryButton>
          </div>
        </div>
      </section>

      {/* Reading Content Examples */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Reading Content Examples</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          <PrimaryButton onClick={() => showArticle(sampleArticle)}>
            Show Article
          </PrimaryButton>
          <PrimaryButton onClick={() => showBlogPost({
            ...sampleArticle,
            title: "Latest Blog Post: Green Energy Trends",
            category: "Blog",
            ctaText: "Read More Articles"
          })}>
            Show Blog Post
          </PrimaryButton>
          <PrimaryButton onClick={() => showNews({
            ...sampleArticle,
            title: "Breaking: New Partnership Announced",
            category: "News",
            content: "Graforce announces strategic partnership to accelerate plasma technology deployment across Europe.",
            ctaText: "Subscribe to Updates"
          })}>
            Show News
          </PrimaryButton>
          <PrimaryButton onClick={() => showCaseStudy({
            title: "Case Study: Industrial Waste to Hydrogen",
            content: `
              <h3>Challenge:</h3>
              <p>A major industrial facility needed to convert waste methane into clean hydrogen while reducing carbon emissions by 90%.</p>
              
              <h3>Solution:</h3>
              <p>Graforce deployed our Methane Plasmalyzer® system, achieving unprecedented conversion rates.</p>
              
              <h3>Results:</h3>
              <ul>
                <li>95% reduction in carbon emissions</li>
                <li>500kg/day hydrogen production</li>
                <li>ROI achieved in 18 months</li>
                <li>Zero waste byproducts</li>
              </ul>
            `,
            author: "Engineering Team",
            date: "September 2025",
            category: "Case Study",
            ctaText: "Discuss Your Project"
          })}>
            Show Case Study
          </PrimaryButton>
        </div>
        
        {/* Direct reading content examples */}
        <div className="mt-6">
          <h3 className="text-lg font-semibold mb-3">Direct Content Examples</h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <PrimaryButton onClick={() => showReadingContent({
              title: "White Paper: Plasma Technology Future",
              content: "Comprehensive analysis of plasma technology trends and future applications in sustainable energy...",
              author: "Research Team",
              date: "October 2025",
              readTime: "15 min read",
              category: "Research",
              tags: ["research", "plasma", "future", "sustainability"],
              ctaText: "Download Full Paper"
            })}>
              White Paper
            </PrimaryButton>
            <PrimaryButton onClick={() => showReadingContent({
              title: "Technical Report: Q3 2025 Results",
              content: "Quarterly technical achievements and breakthrough developments in our plasma systems...",
              author: "Technical Team",
              date: "October 2025",
              readTime: "8 min read",
              category: "Report",
              ctaText: "View All Reports"
            })}>
              Technical Report
            </PrimaryButton>
            <PrimaryButton onClick={() => showReadingContent({
              title: "Press Release: New Facility Opening",
              content: "Graforce opens new manufacturing facility in Munich, expanding production capacity by 300%...",
              date: "October 2025",
              readTime: "3 min read",
              category: "Press Release",
              ctaText: "Media Contact"
            })}>
              Press Release
            </PrimaryButton>
          </div>
        </div>
      </section>

      {/* Specifications Examples */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Technical Specifications Examples</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          <PrimaryButton onClick={() => showSpecificationsContent({
            title: "Plasma Ammonia Cracker® Specs",
            content: {
              specifications: [
                {
                  subtitle: "Processing Capacity",
                  details: "High-throughput ammonia cracking system with excellent efficiency.",
                  points: [
                    "Ammonia input: 50-200 Nm³/h", 
                    "Hydrogen output: 99.95% purity",
                    "Conversion rate: >99.8%",
                    "Energy efficiency: <28 kWh/kg NH₃"
                  ]
                }
              ]
            },
            actions: [
              {
                label: "Get Quote",
                primary: true,
                onClick: "() => sidebarUtils.showProduct('Plasma Ammonia Cracker®', 'Efficient ammonia cracking system')"
              }
            ]
          })}>
            Ammonia Cracker Specs
          </PrimaryButton>
          <PrimaryButton onClick={() => showSpecificationsContent({
            title: "Wastewater Plasmalyzer® Specs", 
            content: {
              specifications: [
                {
                  subtitle: "Treatment Capacity",
                  details: "Advanced wastewater treatment using plasma technology.",
                  points: [
                    "Flow rate: 10-100 m³/h",
                    "COD removal: >95%",
                    "Energy recovery: 40-60%",
                    "Sludge reduction: >90%"
                  ]
                }
              ]
            },
            actions: [
              {
                label: "Learn More",
                primary: true,
                onClick: "() => sidebarUtils.showService('Water Purification', 'Advanced plasma wastewater treatment')"
              }
            ]
          })}>
            Wastewater Treatment Specs
          </PrimaryButton>
          <PrimaryButton onClick={() => showSpecificationsContent(sampleSpecifications)}>
            Methane Plasmalyzer® Specs
          </PrimaryButton>
        </div>
      </section>

      {/* Job Content Examples */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Job Posting Examples</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          <PrimaryButton onClick={() => showJobContent(jobContentExample)}>
            Senior Plasma Engineer
          </PrimaryButton>
          <PrimaryButton onClick={() => showJobContent({
            content: {
              title: "R&D Manager - Sustainable Energy",
              postedOn: "2025-10-15",
              location: "Munich, Germany",
              applyBy: "2025-12-01",
              aboutUs: "Join our research and development team at the forefront of clean energy innovation.",
              aboutUsPoints: [
                "Leading R&D in plasma technology",
                "State-of-the-art research facilities",
                "Collaborative international team",
                "Focus on breakthrough innovations"
              ],
              jobDescription: "Lead our R&D efforts in developing next-generation sustainable energy solutions.",
              jobDescriptionPoints: [
                "Manage research projects and teams",
                "Drive innovation in plasma applications",
                "Collaborate with universities and partners",
                "Oversee patent portfolio development"
              ]
            },
            actions: [
              {
                label: "Apply Now",
                primary: true,
                onClick: "() => sidebarUtils.openContact({ subject: 'R&D Manager Application', showSubject: true })"
              }
            ]
          })}>
            R&D Manager Position
          </PrimaryButton>
          <PrimaryButton onClick={() => showJobContent({
            content: {
              title: "Sales Engineer - International Markets",
              postedOn: "2025-10-20", 
              location: "Berlin, Germany (with travel)",
              applyBy: "2025-11-30",
              aboutUs: "Expand our global reach and bring cutting-edge plasma technology to international markets.",
              aboutUsPoints: [
                "Global market leader in plasma technology",
                "Expanding into new international markets",
                "Strong technical and sales support",
                "Comprehensive training programs"
              ],
              jobDescription: "Drive international sales of our plasma technology solutions across global markets.",
              jobDescriptionPoints: [
                "Develop international client relationships",
                "Provide technical sales support",
                "Conduct product demonstrations",
                "Support contract negotiations"
              ]
            },
            actions: [
              {
                label: "Apply Now",
                primary: true,
                onClick: "() => sidebarUtils.openContact({ subject: 'Sales Engineer Application', showSubject: true })"
              }
            ]
          })}>
            Sales Engineer Position
          </PrimaryButton>
        </div>
      </section>

      {/* Utility Functions (can be called from anywhere) */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Utility Functions (Global Access)</h2>
        <p className="text-gray-600 mb-4">These functions can be called from anywhere in your app, even outside React components:</p>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          <PrimaryButton onClick={() => sidebarUtils.openNavigation()}>
            Utils: Open Nav
          </PrimaryButton>
          <PrimaryButton onClick={() => sidebarUtils.openContact()}>
            Utils: Open Contact
          </PrimaryButton>
          <PrimaryButton onClick={() => sidebarUtils.showProduct("Plasma Generator", "Advanced plasma generation system for industrial applications")}>
            Utils: Show Product
          </PrimaryButton>
          <PrimaryButton onClick={() => sidebarUtils.showService("CO2-Free Energy", "Revolutionary approach to clean energy generation")}>
            Utils: Show Service
          </PrimaryButton>
          <PrimaryButton onClick={() => sidebarUtils.showArticle("Utils Article", "This article was opened using utility functions! You can call these from event handlers, API callbacks, or any JavaScript context.")}>
            Utils: Show Article
          </PrimaryButton>
          <PrimaryButton onClick={() => sidebarUtils.showNews("Breaking News", "Important company announcement using utility functions.", "October 30, 2025")}>
            Utils: Show News
          </PrimaryButton>
          <PrimaryButton onClick={() => sidebarUtils.openCustom(jobContentExample, "Job Opening")}>
            Utils: Show Job
          </PrimaryButton>
          <PrimaryButton onClick={() => sidebarUtils.close()}>
            Utils: Close Sidebar
          </PrimaryButton>
        </div>
      </section>

      {/* Code Examples */}
      <section>
        <h2 className="text-2xl font-semibold mb-4">Implementation Examples</h2>
        <div className="space-y-6">
          
          {/* React Hooks Usage */}
          <div className="bg-gray-100 p-4 rounded-lg">
            <h3 className="font-semibold mb-3">1. React Hooks Usage (Inside Components)</h3>
            <pre className="text-sm text-gray-800 mb-4 overflow-x-auto bg-white p-3 rounded border">
{`// Basic hooks
import { useSidebarActions, useContactSidebar, useReadingSidebar } from '@/hooks/useSidebarActions';

const MyComponent = () => {
  const { 
    showNavigation, 
    showContactForm, 
    showReadingContent,
    showSpecificationsContent,
    showJobContent,
    showCustomContent,
    isOpen
  } = useSidebarActions();
  
  const { inquireAboutProduct, inquireAboutService, generalInquiry, supportRequest } = useContactSidebar();
  const { showArticle, showBlogPost, showNews, showCaseStudy } = useReadingSidebar();
  
  return (
    <div>
      <button onClick={showNavigation}>Menu</button>
      <button onClick={() => showContactForm()}>Contact</button>
      <button onClick={() => inquireAboutProduct("Methane Plasmalyzer®")}>Product Inquiry</button>
      <button onClick={() => showArticle(articleData)}>Read Article</button>
      <p>Sidebar is {isOpen ? 'open' : 'closed'}</p>
    </div>
  );
};`}
            </pre>
          </div>

          {/* Utility Functions Usage */}
          <div className="bg-gray-100 p-4 rounded-lg">
            <h3 className="font-semibold mb-3">2. Global Utility Functions (Anywhere in App)</h3>
            <pre className="text-sm text-gray-800 mb-4 overflow-x-auto bg-white p-3 rounded border">
{`// Can be called from anywhere - event handlers, API callbacks, etc.
import { sidebarUtils } from '@/utils/sidebarUtils';

// Basic functions
sidebarUtils.openNavigation();
sidebarUtils.openContact();
sidebarUtils.close();

// Convenience methods
sidebarUtils.showProduct("Product Name", "Description");
sidebarUtils.showService("Service Name", "Description");
sidebarUtils.showArticle("Title", "Content", "Author", "Date");
sidebarUtils.showNews("News Title", "News content", "2025-10-30");

// Advanced usage
sidebarUtils.openContact({
  subject: "Custom Subject",
  showSubject: true,
  additionalInfo: "Pre-filled information"
});`}
            </pre>
          </div>

          {/* Content Structure Examples */}
          <div className="bg-gray-100 p-4 rounded-lg">
            <h3 className="font-semibold mb-3">3. Content Structure Examples</h3>
            <pre className="text-sm text-gray-800 mb-4 overflow-x-auto bg-white p-3 rounded border">
{`// Job Content Structure
const jobData = {
  content: {
    title: "Senior Engineer",
    postedOn: "2025-10-30",
    location: "Berlin, Germany",
    applyBy: "2025-11-30",
    aboutUs: "Company description...",
    aboutUsPoints: ["Point 1", "Point 2", "Point 3"],
    jobDescription: "Job details...",
    jobDescriptionPoints: ["Responsibility 1", "Responsibility 2"]
  },
  actions: [
    {
      label: "Apply Now",
      primary: true,
      onClick: "() => sidebarUtils.openContact({ subject: 'Job Application' })"
    }
  ]
};

// Specifications Content Structure
const specsData = {
  title: "Product Specifications",
  content: {
    specifications: [
      {
        subtitle: "Performance",
        details: "High-performance system specifications",
        points: ["Spec 1", "Spec 2", "Spec 3"]
      }
    ]
  },
  actions: [/* action buttons */]
};

// Reading Content Structure
const articleData = {
  title: "Article Title",
  content: "HTML or text content...",
  author: "Author Name",
  date: "2025-10-30",
  readTime: "5 min read",
  category: "Technology",
  tags: ["tag1", "tag2"],
  relatedLinks: [{ title: "Link", url: "https://..." }],
  ctaText: "Contact Us",
  ctaAction: "contact"
};`}
            </pre>
          </div>

          {/* Advanced Examples */}
          <div className="bg-gray-100 p-4 rounded-lg">
            <h3 className="font-semibold mb-3">4. Advanced Usage Patterns</h3>
            <pre className="text-sm text-gray-800 overflow-x-auto bg-white p-3 rounded border">
{`// Custom React Component Content
const customComponent = (
  <div>
    <h2>Custom Component</h2>
    <p>Any React component can be displayed</p>
    <button onClick={() => alert('Interactive!')}>Click Me</button>
  </div>
);
sidebarUtils.openCustom(customComponent, "Custom Title");

// Complex Contact Form
sidebarUtils.openContact({
  subject: "Partnership Inquiry",
  showSubject: true,
  additionalInfo: "I'm interested in exploring partnership opportunities..."
});

// Chain multiple actions
const showProductDetails = (productName) => {
  // First show specifications
  showSpecificationsContent(productSpecs);
  // Then track user interest
  analytics.track('product_viewed', { product: productName });
};

// Integration with API responses
fetch('/api/articles')
  .then(res => res.json())
  .then(article => {
    sidebarUtils.showArticle(article.title, article.content, article.author);
  });`}
            </pre>
          </div>

        </div>
      </section>
    </div>
  );
};

export default SidebarExamples;